### ISSUE TITLE
Toyota Prius movement topic plugin

### ISSUE THREAD

**Issue by antoniojromero** [JdeRobot/CustomRobots#149]

**Comment by jmplaza** [comment]
We have got the Toyota Prius [already working](https://www.youtube.com/watch?v=WkeZZ23ZjIY) with ROS-Noetic and Gazebo-11, but it was complex as some of their dependencies were outdated. Instead of going on with that plugin we decided to refactor that model to a simpler and more easy to maintain one. Always keeping the Ackermann dynamics and the extendability to integrate new sensors (such as cameras, 2D laser or 3D Lidar).

The new models will be uploaded related to #145 issue
